### ISSUE TITLE
"TypeError: fs.readFileSync is not a function" in React

### ISSUE THREAD

**Issue by keyvanm** [clearnote01/readability#2]
Hi,

Thank you for this amazing library. I am trying to use it in React (in browser) to analyze some text. Unfortunately filesystem doesn't work in browser so I get this error: 
`TypeError: fs.readFileSync is not a function`
```
  12 | 
  13 | var punctuationRE = /[\u2000-\u206F\u2E00-\u2E7F\\'!"#$%&()*+,\-./:;<=>?@[\]^_`{|}~]/g;
  14 | var easyWordsPath = path.join(__dirname, 'easy_words.txt');
> 15 | var easyWords = fs.readFileSync(easyWordsPath, 'utf-8');
  16 | var easyWordSet = new Set(easyWords.split(/\n/g)); // extends Math object
  17 | 
  18 | Math.copySign = function (x, y) {
```

**Comment by clearnote01** [comment]
Yeah, to solve this, I can host the easy_words.txt file and use it with a call here. Thanks for pointing out. I'll try to finish this today.

**Comment by garyo** [comment]
I'm in the same situation -- can't use from the browser. I'll make a local mod to just turn `easy_words.txt` into `easy_words.js` and require it; that should work OK, right? If that works I can submit a PR.

**Comment by clearnote01** [comment]
@garyo merged your PR. I didn't get a chance to get back to this (because time) but thanks to you, we can close the issue now.

**Comment by helenb** [comment]
@clearnote01 I am using https://www.npmjs.com/package/text-readability and seeing the error `Uncaught TypeError: fs.readFileSync is not a function` in the browser. Did your change make it into the npm package? I am using version 1.0.4.
