### ISSUE TITLE
Error due to unresolved package

### ISSUE THREAD

**Issue by helenb** [clearnote01/readability#5]
I believe one further change is needed from the fix that was merged at https://github.com/clearnote01/readability/pull/3

I installed the `text-readability` package direct from this repo, as the package was not up to date. I now see the following issue:

ERROR in ./node_modules/text-readability/main.js
Module not found: Error: Can't resolve 'fs' in '/Users/helen/repos/mq-take-part-research/node_modules/text-readability'

I believe the first line of `main.js` - `const fs = require('fs')` needs to be removed.

**Comment by helenb** [comment]
Please see this PR: https://github.com/clearnote01/readability/pull/6

**Comment by clearnote01** [comment]
Taken and created a release, thanks @helenb
